name: Go

on:
  pull_request:
    branches: [ release ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./main.go

#     - name: Test
#       run: go test -v ./...

#     - name: Create a Release
#       uses: actions/create-release@v1.1.4
#       with:
#         # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
#         tag_name: 
#         # The name of the release. For example, `Release v1.0.1`
#         release_name: 
#         # Text describing the contents of the tag.
#         body: # optional
#         # Path to file with information about the tag.
#         body_path: # optional
#         # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
#         draft: # optional
#         # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
#         prerelease: # optional
#         # Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit
#         commitish: # optional
#         # Owner of the repository if it is not the current one
#         owner: # optional
#         # Repository on which to release.  Used only if you want to create the release on another repo
#         repo: # optional
